name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Installa le dipendenze
        run: bun install

      - name: Compila il progetto
        run: bun run build

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v4

      - name: Carica i file compilati
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
